#!/usr/bin/env bash
# Deploys a mutually compatible Smart Account contract set to Stellar
# Testnet. Unlike deploy-localnet-contracts.sh, this is NOT tied to a
# disposable chain -- every run creates a new, permanent Testnet contract
# set and spends a Friendbot funding. Run it deliberately, not as part of a
# routine reset/bootstrap cycle.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
oz_commit="fbfde388e1b72afa93d6b1c922067879b20e81db"
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/account-sample-testnet.XXXXXX")"
key_dir="${work_dir}/stellar-config"
source_dir="${work_dir}/stellar-contracts"
build_dir="${work_dir}/wasm"

cleanup() {
  rm -rf "${work_dir}"
}
trap cleanup EXIT

for command in git stellar; do
  command -v "${command}" >/dev/null || {
    echo "${command} is required." >&2
    exit 1
  }
done

mkdir -p "${key_dir}" "${build_dir}"
git clone --quiet https://github.com/OpenZeppelin/stellar-contracts.git "${source_dir}"
git -C "${source_dir}" checkout --quiet --detach "${oz_commit}"
[[ "$(git -C "${source_dir}" rev-parse HEAD)" == "${oz_commit}" ]] || {
  echo "OpenZeppelin source revision verification failed." >&2
  exit 1
}

# The temporary CLI config ensures the Friendbot-funded deployer secret never
# reaches the repository or the devcontainer's persistent Stellar config
# volume. `testnet` is a network alias built into the Stellar CLI itself, so
# it resolves under this fresh --config-dir too.
stellar --config-dir "${key_dir}" keys generate testnet-deployer --network testnet --fund >/dev/null
deployer="$(stellar --config-dir "${key_dir}" keys public-key testnet-deployer)"

build_contract() {
  stellar contract build --manifest-path "$1" --out-dir "${build_dir}" --locked
}

build_contract "${source_dir}/examples/multisig-smart-account/account/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/webauthn-verifier/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/ed25519-verifier/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/threshold-policy/Cargo.toml"
build_contract "${repo_root}/contracts/recovery-scope-policy/Cargo.toml"
build_contract "${repo_root}/contracts/time-delay-policy/Cargo.toml"

deploy_wasm() {
  stellar --config-dir "${key_dir}" contract deploy --network testnet --quiet --optimize=false \
    --wasm "$1" --source-account testnet-deployer
}

account_wasm="${build_dir}/multisig_account_example.wasm"
account_wasm_hash="$(stellar --config-dir "${key_dir}" contract install --network testnet --quiet --optimize=false \
  --wasm "${account_wasm}" --source-account testnet-deployer)"
webauthn_verifier="$(deploy_wasm "${build_dir}/multisig_webauthn_verifier_example.wasm")"
ed25519_verifier="$(deploy_wasm "${build_dir}/multisig_ed25519_verifier_example.wasm")"
threshold_policy="$(deploy_wasm "${build_dir}/multisig_threshold_policy_example.wasm")"
recovery_scope_policy="$(deploy_wasm "${build_dir}/recovery_scope_policy.wasm")"
time_delay_policy="$(deploy_wasm "${build_dir}/time_delay_policy.wasm")"

# Public Testnet configuration -- these are contract addresses and a WASM
# hash, not secrets. Unlike frontend/.env.local (localnet, gitignored), this
# file is meant to be committed so the deployed contract set is reviewable.
env_file="${repo_root}/frontend/.env.production"
{
  echo "# Generated by just testnet-deploy on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Public Testnet configuration. Regenerate via 'just testnet-deploy' and"
  echo "# review the diff rather than hand-editing."
  echo "VITE_SMART_ACCOUNT_RPC_URL=https://soroban-testnet.stellar.org"
  echo "VITE_SMART_ACCOUNT_NETWORK_PASSPHRASE=Test SDF Network ; September 2015"
  echo "VITE_SMART_ACCOUNT_WASM_HASH=${account_wasm_hash}"
  echo "VITE_WEBAUTHN_VERIFIER_ADDRESS=${webauthn_verifier}"
  echo "VITE_ED25519_VERIFIER_ADDRESS=${ed25519_verifier}"
  echo "VITE_THRESHOLD_POLICY_ADDRESS=${threshold_policy}"
  echo "VITE_TIME_DELAY_POLICY_ADDRESS=${time_delay_policy}"
  echo "VITE_TIME_DELAY_POLICY_STATUS_ADDRESS=${time_delay_policy}"
  echo "VITE_RECOVERY_SCOPE_POLICY_ADDRESS=${recovery_scope_policy}"
} >"${env_file}"

# Partial backend config for a native 'cargo run' pointed at this contract
# set. Deployment-specific values (RELAY_CHANNELS_API_KEY, RELAY_ALLOWED_ORIGIN,
# RELAY_CHANNELS_URL, RELAY_NETWORK_PASSPHRASE, RECOVERY_NETWORK_PASSPHRASE)
# are not derivable from a contract deployment and are intentionally not
# written here; set them separately before sourcing this file.
backend_env="${repo_root}/.devcontainer/testnet.env"
{
  echo "# Generated by just testnet-deploy. Source before 'cargo run', after also"
  echo "# setting RELAY_CHANNELS_API_KEY / RELAY_ALLOWED_ORIGIN / RELAY_CHANNELS_URL /"
  echo "# RELAY_NETWORK_PASSPHRASE / RECOVERY_NETWORK_PASSPHRASE yourself."
  echo "export RELAY_WASM_HASHES=${account_wasm_hash}"
  echo "export RELAY_MANAGED_ACCOUNT_WASM_HASHES=${account_wasm_hash}"
} >"${backend_env}"

echo "Deployed Testnet contract configuration to ${env_file}."
echo "Wrote RELAY_WASM_HASHES / RELAY_MANAGED_ACCOUNT_WASM_HASHES to ${backend_env}."
echo "The temporary deployer key was discarded; its public address was ${deployer}."
echo
echo "Still manual:"
echo "  - update wrangler.toml's [vars] with the same RELAY_WASM_HASHES /"
echo "    RELAY_MANAGED_ACCOUNT_WASM_HASHES before 'wrangler deploy'"
echo "    (see docs/dev/deployment/cloudflare.md)."
echo "  - append a dated record with these addresses to"
echo "    docs/dev/deployment/testnet.md."
