#!/usr/bin/env bash
# Deploys a mutually compatible, local-only Smart Account contract set.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
oz_commit="fbfde388e1b72afa93d6b1c922067879b20e81db"
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/account-sample-localnet.XXXXXX")"
key_dir="${work_dir}/stellar-config"
source_dir="${work_dir}/stellar-contracts"
build_dir="${work_dir}/wasm"

cleanup() {
  rm -rf "${work_dir}"
}
trap cleanup EXIT

for command in git stellar curl; do
  command -v "${command}" >/dev/null || {
    echo "${command} is required." >&2
    exit 1
  }
done

export STELLAR_RPC_URL="${STELLAR_RPC_URL:-http://stellar-localnet:8000/rpc}"
export STELLAR_FRIENDBOT_URL="${STELLAR_FRIENDBOT_URL:-http://stellar-localnet:8000/friendbot}"
export STELLAR_NETWORK_PASSPHRASE="${STELLAR_NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"

mkdir -p "${key_dir}" "${build_dir}"
git clone --quiet https://github.com/OpenZeppelin/stellar-contracts.git "${source_dir}"
git -C "${source_dir}" checkout --quiet --detach "${oz_commit}"
[[ "$(git -C "${source_dir}" rev-parse HEAD)" == "${oz_commit}" ]] || {
  echo "OpenZeppelin source revision verification failed." >&2
  exit 1
}

# The temporary CLI config ensures the Friendbot-funded deployer secret never
# reaches the repository or the devcontainer's persistent Stellar config volume.
stellar --config-dir "${key_dir}" keys generate localnet-deployer >/dev/null
deployer="$(stellar --config-dir "${key_dir}" keys public-key localnet-deployer)"
curl --fail --silent --show-error "${STELLAR_FRIENDBOT_URL}?addr=${deployer}" >/dev/null

build_contract() {
  stellar contract build --manifest-path "$1" --out-dir "${build_dir}" --locked
}

build_contract "${source_dir}/examples/multisig-smart-account/account/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/webauthn-verifier/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/ed25519-verifier/Cargo.toml"
build_contract "${source_dir}/examples/multisig-smart-account/threshold-policy/Cargo.toml"
build_contract "${repo_root}/contracts/recovery-scope-policy/Cargo.toml"
build_contract "${repo_root}/contracts/time-delay-policy/Cargo.toml"

deploy_wasm() {
  stellar --config-dir "${key_dir}" contract deploy --quiet --optimize=false \
    --wasm "$1" --source-account localnet-deployer
}

account_wasm="${build_dir}/multisig_account_example.wasm"
account_wasm_hash="$(stellar --config-dir "${key_dir}" contract install --quiet --optimize=false \
  --wasm "${account_wasm}" --source-account localnet-deployer)"
webauthn_verifier="$(deploy_wasm "${build_dir}/multisig_webauthn_verifier_example.wasm")"
ed25519_verifier="$(deploy_wasm "${build_dir}/multisig_ed25519_verifier_example.wasm")"
threshold_policy="$(deploy_wasm "${build_dir}/multisig_threshold_policy_example.wasm")"
recovery_scope_policy="$(deploy_wasm "${build_dir}/recovery_scope_policy.wasm")"
time_delay_policy="$(deploy_wasm "${build_dir}/time_delay_policy.wasm")"

env_file="${repo_root}/frontend/.env.local"
{
  echo "# Generated by just localnet-deploy. Do not edit; it is replaced on the next deployment."
  echo "VITE_SMART_ACCOUNT_RPC_URL=https://localhost:5173/rpc"
  echo "VITE_SMART_ACCOUNT_NETWORK_PASSPHRASE=${STELLAR_NETWORK_PASSPHRASE}"
  echo "VITE_SMART_ACCOUNT_WASM_HASH=${account_wasm_hash}"
  echo "VITE_WEBAUTHN_VERIFIER_ADDRESS=${webauthn_verifier}"
  echo "VITE_ED25519_VERIFIER_ADDRESS=${ed25519_verifier}"
  echo "VITE_SMART_ACCOUNT_RELAYER_URL=/api/relay"
  echo "VITE_THRESHOLD_POLICY_ADDRESS=${threshold_policy}"
  echo "VITE_RECOVERY_SCOPE_POLICY_ADDRESS=${recovery_scope_policy}"
  echo "VITE_TIME_DELAY_POLICY_ADDRESS=${time_delay_policy}"
  echo "VITE_TIME_DELAY_POLICY_STATUS_ADDRESS=${time_delay_policy}"
  echo "VITE_L4_OPERATOR_ADDRESS=${deployer}"
} >"${env_file}"

backend_env="${repo_root}/.devcontainer/localnet.env"
{
  echo "# Generated by just localnet-deploy. Source this before cargo run."
  echo "export RELAY_WASM_HASHES=${account_wasm_hash}"
  echo "export RELAY_MANAGED_ACCOUNT_WASM_HASHES=${account_wasm_hash}"
} >"${backend_env}"

echo "Deployed local contract configuration to ${env_file}."
echo "The temporary deployer key was discarded; its public address is ${deployer}."
echo "Start the API with 'just api' and restart Vite if it was already running."
